version: '3'

services:
  snykdemoapp:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: snykdemoapp
    image: snykdemoapp
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      app-network:
        aliases:
          - snykdemoapp

networks:
  app-network:
    name: app-network

app_db:
    image: mysql:5.7
    container_name: app_db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      app-network:
        aliases:
          - app_db

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - app_db
    environment:
      PMA_HOST: app_db
      PMA_PORT: 3306
    ports:
      - '8080:80'
    networks:
      app-network:
        aliases:
          - phpmyadmin
